#!/bin/bash -e
echo "testing runshtrigger!!!"
echo SAMPLE_SCRIPT=res2
echo IS_FORK=$RES1_IS_FORK
echo IS_PR=$RES2_IS_PULL_REQUEST
echo REPONAME=$RES2_REPO_FULL_NAME
echo PRREPONAME=$RES2_PULL_REQUEST_REPO_FULL_NAME